# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sparks < Formula
  desc "Knowledge base runtime for AI agents — a single Go binary that any harness can drive"
  homepage "https://github.com/yogirk/sparks"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yogirk/sparks/releases/download/v0.2.0/sparks_0.2.0_darwin_amd64.tar.gz"
      sha256 "2e168ecc8c4991ef64a3672c5b1f38aaf39bf6eafaf57359eabe2aed3a7f1e6c"

      define_method(:install) do
        bin.install "sparks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yogirk/sparks/releases/download/v0.2.0/sparks_0.2.0_darwin_arm64.tar.gz"
      sha256 "2c825c51c09397e988679ce2b1c4e7baf3b3eed2b760998af887d3fce7ba9d29"

      define_method(:install) do
        bin.install "sparks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yogirk/sparks/releases/download/v0.2.0/sparks_0.2.0_linux_amd64.tar.gz"
      sha256 "ea2fa7f351c4f1553d6620bb16a9ac6cf29d8923d89a50a1bb1c7738d48ba4ad"
      define_method(:install) do
        bin.install "sparks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yogirk/sparks/releases/download/v0.2.0/sparks_0.2.0_linux_arm64.tar.gz"
      sha256 "3b2371a823eb5e196df89288cae436cd6ba3e87ebb8e109fd7225cc4fa83108f"
      define_method(:install) do
        bin.install "sparks"
      end
    end
  end

  test do
    system "#{bin}/sparks", "--version"
  end
end
