# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tgcp < Formula
  desc "Terminal UI for Google Cloud Platform"
  homepage "https://github.com/yogirk/tgcp"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yogirk/tgcp/releases/download/v0.4.1/tgcp_0.4.1_darwin_amd64.tar.gz"
      sha256 "a19bbdd6c541e5a36b86e3a1f2e5456c652beaad4bc64d4c4486d001be005c97"

      define_method(:install) do
        bin.install "tgcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yogirk/tgcp/releases/download/v0.4.1/tgcp_0.4.1_darwin_arm64.tar.gz"
      sha256 "0baef77c8a6a5c3b9a5a5192bb0b75c1c7c21547810827197558f44b03761156"

      define_method(:install) do
        bin.install "tgcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yogirk/tgcp/releases/download/v0.4.1/tgcp_0.4.1_linux_amd64.tar.gz"
      sha256 "fe2152cd891d8f30657be01cb2030acde3fbbe474d36c5233687106d98b142ec"
      define_method(:install) do
        bin.install "tgcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yogirk/tgcp/releases/download/v0.4.1/tgcp_0.4.1_linux_arm64.tar.gz"
      sha256 "adaea8a742388e3a8b5588cafe8024a957cc2a4dbdf605d4938874d4fe8fedfb"
      define_method(:install) do
        bin.install "tgcp"
      end
    end
  end

  test do
    system "#{bin}/tgcp", "--version"
  end
end
