# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tgcp < Formula
  desc "Terminal UI for Google Cloud Platform"
  homepage "https://github.com/yogirk/tgcp"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yogirk/tgcp/releases/download/v0.2.0/tgcp_0.2.0_darwin_amd64.tar.gz"
      sha256 "2b1435630c655fc981b13c542f21b0e28fe6fea4bb9d8eeb7a7d831df29f1676"

      def install
        bin.install "tgcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yogirk/tgcp/releases/download/v0.2.0/tgcp_0.2.0_darwin_arm64.tar.gz"
      sha256 "b49cd50fcb99f15190c64eb81913d1df2b2d1e1091edc849b507b4cbaa7817fa"

      def install
        bin.install "tgcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yogirk/tgcp/releases/download/v0.2.0/tgcp_0.2.0_linux_amd64.tar.gz"
      sha256 "c3d4faf5a70b350ac981ce41e625f30855e0a7936ec2b673d170aa002bcd9cfc"
      def install
        bin.install "tgcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yogirk/tgcp/releases/download/v0.2.0/tgcp_0.2.0_linux_arm64.tar.gz"
      sha256 "ca93a3eb842b69f8455a64c34c5ed8b244cd82117ff0d91fe49e71521dd38d09"
      def install
        bin.install "tgcp"
      end
    end
  end

  test do
    system "#{bin}/tgcp", "--version"
  end
end
